export const facts = [
  'Honey never spoils; archaeologists have tasted 3,000-year-old honey.',
  'Octopuses have three hearts and blue blood.',
  'A day on Venus is longer than a year on Venus.',
  'Bananas are berries, but strawberries are not.',
  'The Eiffel Tower can grow about 15 cm taller in summer heat.',
  'Sharks have been around longer than trees.',
  'Your brain uses roughly 20% of your body’s energy.',
  'A bolt of lightning is hotter than the surface of the Sun.',
  'Some turtles can breathe through their butts during winter.',
  'The shortest war in history lasted about 38 minutes.',
  'Cleopatra lived closer to the Moon landing than to the pyramids.',
  'There are more possible chess games than atoms in the observable universe.',
  'Wombat poop is cube-shaped to stop it rolling away.',
  'A group of flamingos is called a flamboyance.',
  'The human stomach gets a new lining every few days.',
  'An asteroid impact helped wipe out the dinosaurs 66 million years ago.',
  'The Great Wall of China is not visible from space with the naked eye.',
  'Ants can carry objects many times their own weight.',
  'Some frogs freeze solid in winter and thaw back to life in spring.',
  'The first computer bug was an actual moth found in 1947.',
  'A teaspoon of neutron star material would weigh billions of tons on Earth.',
  'The Moon is moving away from Earth by about 3.8 cm each year.',
  'Dolphins have signature whistles that act like names.',
  'The smell of rain is caused partly by a molecule called geosmin.',
  'Spiders can’t fly, but many “balloon” on silk threads to travel.',
  'Humans share about 60% of their DNA with bananas.',
  'Penguins propose with pebbles in some species.',
  'The longest English word without a vowel is “rhythms”.',
  'The coldest place in the universe may be the Boomerang Nebula.',
  'A single cloud can weigh more than a million pounds.',
  'The “fear center” in your brain is the amygdala.',
  'Your eyes can’t see the world in “high definition”; your brain fills gaps.',
  'The first Olympic Games were held in Olympia in 776 BCE.',
  'The first pizza delivery is recorded in Naples in 1889.',
  'Cats can make over 100 vocal sounds; dogs make around 10.',
  'Some mushrooms can glow in the dark (bioluminescence).',
  'A snail can sleep for up to three years in harsh conditions.',
  'The heart of a blue whale is about the size of a small car.',
  'Cows have best friends and get stressed when separated.',
  'The Amazon rainforest produces a significant share of Earth’s oxygen.',
  'The word “robot” comes from a Czech word meaning forced labor.',
  'The first printed book was produced in China, not Europe.',
  'A crocodile can’t stick its tongue out.',
  'The hottest chili pepper can feel like being burned due to capsaicin.',
  'The human body has more bacterial cells than human cells (by count).',
  'A violin’s sound comes largely from its wooden body, not just strings.',
  'Saturn could float in water because it’s less dense than water.',
  'Butterflies taste with their feet.',
  'The strongest muscle by weight is often said to be the jaw muscle.'
] as const
